### ISSUE TITLE
Does xvisbell is maintained and do you accept feature requests?

### ISSUE THREAD

**Issue by aabc** [rianhunter/xvisbell#1]
Thanks for very useful (for me) software! Do you still develop it and accept feature requests?

**Comment by adamhotep** [comment]
I've made a few minor tweaks in my fork and may be able to make more.  What would you like?

Disclaimer: I've more rusty than not when it comes to C/C++, so my actions will be limited to minor edits and wrapper scripts.  @rianhunter would be needed for something more significant, but if you don't ask, there's no way you'll get either of us to do it ;-)

**Comment by rianhunter** [comment]
Yes this software is maintained insofar as PR will be reviewed and accepted.

It is intentionally simple so I am loath to accept new features that complicate the code. For those, it would be better if you maintained your own forks.
